# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: jakzal/phpqa:php7.4


pipelines:
  default:
    - parallel:
        - step:
            name: before_script
            script:
              - composer install
        - step:
            name: security-checker
            script:
              - local-php-security-checker  --path=./composer.lock
        - step:
            name: phpcs
            script:
              - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
        - step:
            name: phpstan
            script:
              - phpstan analyse ./src
        - step:
            name: twig-lint
            script:
              - twig-lint lint ./templates
        - step:
            name: phpunit
            script:
              - apt-get update && apt-get install -y git libzip-dev
              - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
              - docker-php-ext-install mysqli pdo pdo_mysql zip
              - php bin/console doctrine:database:drop --force --env=test
              - php bin/console doctrine:database:create --env=test
              - php bin/console doctrine:migration:migrate --env=test --no-interaction
              - php bin/phpunit
              